
name: Build/publish Docker image

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'src/test/**'
      - 'docker-compose.yaml'
      - '*.md'
      - 'LICENSE'

jobs:
  build-publish-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-build-publish-image.yml@main
    with:
      image-name: eidas-demo-country-ca
      application-type: docker
      application-path: ./docker/
    secrets: inherit

  call-update-image:
    uses: felleslosninger/github-workflows/.github/workflows/ci-call-update-image.yml@main
    needs: build-publish-image
    with:
      application-name: eidas-demo-country-ca
      deployment-environment: systest
      image-digest: ${{ needs.build-publish-image.outputs.image-digest }}
      image-name: eidas-demo-country-ca
      image-version: ${{ needs.build-publish-image.outputs.image-version }}
      kubernetes-repo: idporten-cd
      product-name: eidas
    secrets: inherit
