
name: Build Dockerfile

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: my-local-registery/eidas-demo-country-ca
      DOCKLE_HOST: "unix:///var/run/docker.sock"
      TRIVY_OFFLINE_SCAN: false
    steps:
      - name: Set imagetag as env variable
        run: echo "IMAGETAG=$(date +'%Y-%m-%d-%H%M')-${GITHUB_SHA::8}" >> "$GITHUB_ENV"
      - uses: actions/checkout@v4
      - name: Build the tagged Docker image
        run: docker build --tag ${{ env.IMAGE_NAME}}:${{env.IMAGETAG}} --file docker/Dockerfile .
      - uses: anchore/sbom-action@v0
        with:
          image: ${{ env.IMAGE_NAME}}:${{env.IMAGETAG}}
      - name: Run Trivy vulnerability scanner
        uses: felleslosninger/github-workflows/.github/actions/trivy-scan@main
        with:
          image-ref: "${{ env.IMAGE_NAME }}:${{env.IMAGETAG}}"
          os-exit-code: "1"

